services:
  register:
    build:
      args:
        - target=registration
      dockerfile: "Dockerfile"
    environment:
      - MONGO_USER=brucebernard
      - MONGO_PASS=admin
      - MONGO_HOST=db
  ballot:
    build:
      args:
        - target=ballot
      dockerfile: "Dockerfile"
    environment:
      - MONGO_USER=brucebernard
      - MONGO_PASS=admin
      - MONGO_HOST=db
  admin:
    build:
      args:
        - target=admin
      dockerfile: "Dockerfile"
    environment:
      - MONGO_USER=brucebernard
      - MONGO_PASS=admin
      - MONGO_HOST=db
  revproxy:
    build:
      dockerfile: Dockerfile.nginx
  db:
    build:
      dockerfile: Dockerfile.db
    environment:
      MONGO_INITDB_ROOT_USERNAME: brucebernard
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: hacksoc
