services:
  register:
    build:
      args:
        - target=registration
      dockerfile: "Dockerfile"
    env_file: ".env"
  ballot:
    build:
      args:
        - target=ballot
      dockerfile: "Dockerfile"
    env_file: ".env"
  admin:
    build:
      args:
        - target=admin
      dockerfile: "Dockerfile"
    env_file: ".env"
  revproxy:
    ports:
      - 80:8000
    build:
      dockerfile: Dockerfile.nginx
